MAX_EMAIL_LENGTH = 254
MAX_USER_VALUE_LENGTH = 150
MAX_RECIPE_VALUE_LENGTH = 200
MAX_TAG_COLOR_LENGTH = 7
TAG_COLOR_REGEX = r'^#([0-9a-fA-F]{3}){1,2}\Z'
NAME_REGEX = r'^[A-Za-zа-яА-Я ]+$'
SHOPPING_CART_FILENAME = 'shopping-list.txt'
