version: '3.3'

volumes:
  pg_data:
  static:
  backend_static:
  backend_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ../backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file: .env
    #command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/result_build/build

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/backend_static
      - backend_media:/backend_media
