# Generated by Django 3.2.16 on 2023-10-19 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message="Поле name может содержать только русские и латинские буквы и символы '@.+-_'", regex='^[A-Za-zа-яА-Я ]*$')], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message="Поле name может содержать только русские и латинские буквы и символы '@.+-_'", regex='^[A-Za-zа-яА-Я ]*$')], verbose_name='фамилия'),
        ),
    ]
