# Generated by Django 3.2.16 on 2023-10-20 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231019_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Поле name может содержать только русские и латинские буквы и пробел.', regex='^[A-Za-zа-яА-Я ]+$')], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Поле name может содержать только русские и латинские буквы и пробел.', regex='^[A-Za-zа-яА-Я ]+$')], verbose_name='фамилия'),
        ),
    ]
